#!/usr/bin/env python3
"""Stage 0 — Run OpenMM OPES-MD for all three diagnostic systems.

Ground-truth reference data MUST come from independent physical simulations.
This script drives ``genai_tps.simulation.openmm_md_runner`` (AMBER14 + explicit
TIP3P solvent in a periodic box with PME, Langevin 300 K, 2 fs timestep, real
PLUMED OPES bias forces).  By default it uses **3D CVs** (``lig_rmsd``,
``lig_dist``, ``lig_contacts``) with **``OPES_METAD_EXPLORE``**; pass
``--bias-cv 2d`` or ``--opes-bias-style metad`` to fall back to the older 2D /
OPES_METAD setup.

Boltz ``processed/structures/*.npz`` files supply **topology** (atom ordering for
the OpenMM bridge) but typically contain **placeholder coordinates**.  After
preprocessing, this script runs one Boltz-2 diffusion sample to produce a
self-consistent 3D pose, saves it to ``boltz_init_coords.npz``, and passes that
file as ``--frame-npz`` to the MD runner.  Default sampling and recycling match
the official ``boltz predict`` CLI (``docs/prediction.md`` on the Boltz repo):
``--sampling_steps 200``, ``--recycling_steps 3``.  The resulting OpenMM trajectory remains an AMBER + explicit-solvent reference
independent of any TPS checkpoints.

Why OpenMM, not TPS trajectories?
    TPS trajectories are generated by the Boltz-2 model being evaluated.
    Using them as training data would be circular.  OpenMM MD with an explicit
    force field (AMBER14) provides a model-independent physical reference that
    obeys the Boltzmann distribution for a known energy function.

Pipeline role:
    00_generate_reference_data  →  01_assemble_datasets  →  02_finetune_boltz2

Outputs (one subdirectory per system)::

    outputs/campaign/case{1,2,3}/openmm_opes_md/
        wdsm_samples/wdsm_step_*.npz   # per-frame coordinate + logw shards
        cv_log.json                    # step / cv / logw time series
        opes_states/COLVAR             # PLUMED CV / bias time series
        opes_states/KERNELS            # OPES kernel history
        opes_states/STATE              # periodic compressed OPES state
        opes_states/STATE_EXPANDED    # optional: OPES_EXPANDED checkpoint (see --opes-expanded-temp-max)
        opes_states/OPES_EXPANDED_DELTAFS  # optional: expanded-ensemble DeltaF log
        plumed_opes.dat                # PLUMED input deck used by OpenMM
        md_summary.json                # timing and hyperparameter record

Optional postprocessing (after MD finishes): run
``scripts/campaign/01b_plumed_colvar_fes.py`` on the same ``--out`` tree, or
``01_assemble_datasets.py --plumed-fes``, to write
``opes_states/fes_reweighted_2d.dat`` from ``COLVAR`` via PLUMED's OPES
reweighting script (use matching ``--cv`` / dimensions when COLVAR has three
biased CV columns).

For COLVAR path stability with a PLUMED build from the patched ``plumed2``
submodule (see ``scripts/build_plumed_opes.sh``), pass ``--plumed-colvar-heavy-flush``.

Example::

    # Set SCRATCH or BOLTZ_CACHE so checkpoints/molecule data land on scratch, not HOME.
    # Quick test (100 k MD steps per system; Boltz + OpenMM default to GPU):
    python scripts/campaign/00_generate_reference_data.py \
        --n-steps 100000 --out outputs/campaign

    # Or pass an explicit cache root:
    #   --cache /scratch/$USER/.boltz

    # Production (5 M MD steps):
    python scripts/campaign/00_generate_reference_data.py \
        --n-steps 5000000 --out outputs/campaign

    CPU-only fallback (CI or machines without a GPU; very slow for Boltz):
    ``--device cpu --platform CPU``.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import numpy as np
import torch

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT / "src" / "python") not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT / "src" / "python"))

from genai_tps.backends.boltz.cache_paths import default_boltz_cache_dir
from genai_tps.simulation.openmm_md_runner import (
    _parse_comma_int_list,
    _parse_oneopes_contact_pairs_boltz,
    _parse_opes_nlist_parameters,
)
from genai_tps.subprocess_support import child_env_with_repo_src_python
from genai_tps.utils.compute_device import (
    cuda_device_index_for_openmm,
    maybe_set_torch_cuda_current_device,
    parse_torch_device,
)

# ---------------------------------------------------------------------------
# System definitions — one entry per diagnostic case
# ---------------------------------------------------------------------------

_SYSTEMS = [
    {
        "name": "case1_mek1_fzc_novel",
        "yaml": "inputs/tps_diagnostic/case1_mek1_fzc_novel.yaml",
        "cif": "inputs/tps_diagnostic/reference_structures/7XLP.cif",
        "ligand_ccd": "FZC",
        "description": "Case 1 — MEK1+FZC novel (negative control)",
    },
    {
        "name": "case2_cdk2_atp_wildtype",
        "yaml": "inputs/tps_diagnostic/case2_cdk2_atp_wildtype.yaml",
        "cif": "inputs/tps_diagnostic/reference_structures/1B38.cif",
        "ligand_ccd": "ATP",
        "description": "Case 2 — CDK2+ATP WT memorised (positive control)",
    },
    {
        "name": "case3_cdk2_atp_packed",
        "yaml": "inputs/tps_diagnostic/case3_cdk2_atp_packed.yaml",
        "cif": "inputs/tps_diagnostic/reference_structures/1B38.cif",
        "ligand_ccd": "ATP",
        "description": "Case 3 — CDK2+ATP Phe-packed adversarial",
    },
]


def _write_merged_campaign_log(out_root: Path, new_entries: list) -> None:
    """Merge *new_entries* into ``00_reference_data_log.json`` (locked, multi-process safe).

    Parallel ``--cases N`` runs share the same ``--out`` root; each process merges
    completed rows without clobbering siblings.
    """
    import fcntl

    log_path = out_root / "00_reference_data_log.json"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    with open(log_path, "a+", encoding="utf-8") as fh:
        fcntl.flock(fh.fileno(), fcntl.LOCK_EX)
        try:
            fh.seek(0)
            raw = fh.read()
            prev: list = []
            if raw.strip():
                try:
                    loaded = json.loads(raw)
                    if isinstance(loaded, list):
                        prev = loaded
                except json.JSONDecodeError:
                    prev = []

            by_case: dict[str, dict] = {}
            for e in prev:
                if isinstance(e, dict) and isinstance(e.get("case"), str):
                    by_case[e["case"]] = e
            for e in new_entries:
                if isinstance(e, dict) and isinstance(e.get("case"), str):
                    by_case[e["case"]] = e

            ordered: list = []
            for sys_def in _SYSTEMS:
                name = sys_def["name"]
                if name in by_case:
                    ordered.append(by_case[name])

            payload = json.dumps(ordered, indent=2) + "\n"
            fh.seek(0)
            fh.truncate()
            fh.write(payload)
            fh.flush()
        finally:
            fcntl.flock(fh.fileno(), fcntl.LOCK_UN)


def _boltz_prep_for_openmm(
    yaml_path: Path,
    out_dir: Path,
    cache: Path,
    device: str,
    *,
    init_sampling_steps: int,
    recycling_steps: int,
):
    """Preprocess inputs, load Boltz-2, and return a bundle plus topology NPZ path.

    The processed ``structures/*.npz`` defines OpenMM–Boltz atom ordering but
    often has placeholder (zero) coordinates.  Call
    :func:`~genai_tps.backends.boltz.inference.predict_sample_atom_coords_numpy`
    on the returned bundle to obtain a self-consistent 3D pose for MD.
    """
    import torch

    from genai_tps.backends.boltz.inference import build_boltz_inference_session

    prep_dir = out_dir / "boltz_prep"
    bundle = build_boltz_inference_session(
        yaml_path=yaml_path,
        cache=cache,
        boltz_prep_dir=prep_dir,
        device=torch.device(device),
        diffusion_steps=int(init_sampling_steps),
        recycling_steps=int(recycling_steps),
        kernels=False,
    )
    topo_npz = bundle.topo_npz
    if topo_npz is None or not topo_npz.is_file():
        raise RuntimeError(
            f"Boltz preprocessing produced no topology NPZ under {prep_dir}. "
            "Check that the YAML and Boltz cache are correct."
        )
    print(f"  [prep] Topology NPZ: {topo_npz}", flush=True)
    return bundle, topo_npz


def _run_openmm_md(
    *,
    topo_npz: Path,
    frame_npz: Path | None,
    mol_dir: Path,
    out_dir: Path,
    n_steps: int,
    save_every: int,
    deposit_pace: int,
    opes_barrier: float,
    opes_biasfactor: float,
    opes_sigma: str,
    temperature: float,
    pocket_radius: float,
    platform: str,
    minimize_steps: int,
    progress_every: int,
    save_opes_every: int,
    opes_restart: Path | None,
    opes_mode: str,
    opes_kernel_cutoff: float | None,
    opes_nlist_parameters: tuple[float, float] | None,
    plumed_colvar_heavy_flush: bool,
    openmm_device_index: int | None = None,
    log_gpu_util: bool = False,
    gpu_util_interval: float = 0.1,
    gpu_util_out: Path | None = None,
    bias_cv: str = "2d",
    opes_explore: bool = False,
    opes_wall_dist: float | None = None,
    opes_wall_kappa: float = 200.0,
    coordination_r0: float = 4.5,
    opes_expanded_temp_max: float | None = None,
    opes_expanded_pace: int = 50,
    oneopes_axis_p0_boltz: list[int] | None = None,
    oneopes_axis_p1_boltz: list[int] | None = None,
    oneopes_contact_pairs_boltz: list[tuple[int, int]] | None = None,
    oneopes_hydration_boltz: list[int] | None = None,
    oneopes_water_oxygen_plumed: list[int] | None = None,
    oneopes_water_pace: int = 40_000,
    oneopes_water_barrier: float = 3.0,
    oneopes_water_biasfactor: float = 5.0,
    oneopes_water_sigma: float = 0.15,
    oneopes_auto_hydration: bool = True,
    oneopes_hydration_max_sites: int = 5,
    oneopes_hydration_use_3drism: bool = True,
    oneopes_hydration_min_density: float = 0.5,
) -> None:
    """Invoke the OpenMM OPES-MD runner via subprocess for isolation."""
    md_script = _REPO_ROOT / "scripts" / "run_openmm_opes_md.py"
    cmd = [
        sys.executable, str(md_script),
        "--topo-npz", str(topo_npz),
        "--out", str(out_dir),
        "--n-steps", str(n_steps),
        "--save-every", str(save_every),
        "--deposit-pace", str(deposit_pace),
        "--opes-barrier", str(opes_barrier),
        "--opes-biasfactor", str(opes_biasfactor),
        "--opes-sigma", opes_sigma,
        "--temperature", str(temperature),
        "--pocket-radius", str(pocket_radius),
        "--platform", platform,
        "--minimize-steps", str(minimize_steps),
        "--progress-every", str(progress_every),
        "--save-opes-every", str(save_opes_every),
        "--opes-mode", opes_mode,
        "--mol-dir", str(mol_dir),
        "--bias-cv", str(bias_cv),
    ]
    if opes_explore:
        cmd.append("--opes-explore")
    if opes_wall_dist is not None:
        cmd += ["--opes-wall-dist", str(float(opes_wall_dist))]
        cmd += ["--opes-wall-kappa", str(float(opes_wall_kappa))]
    cmd += ["--coordination-r0", str(float(coordination_r0))]
    if opes_expanded_temp_max is not None:
        cmd += [
            "--opes-expanded-temp-max",
            str(float(opes_expanded_temp_max)),
            "--opes-expanded-pace",
            str(int(opes_expanded_pace)),
        ]
    if opes_restart is not None:
        cmd += ["--opes-restart", str(opes_restart)]
    if opes_kernel_cutoff is not None:
        cmd += ["--opes-kernel-cutoff", str(opes_kernel_cutoff)]
    if opes_nlist_parameters is not None:
        a, b = opes_nlist_parameters
        cmd += ["--opes-nlist-parameters", f"{a},{b}"]
    if frame_npz is not None:
        cmd += ["--frame-npz", str(frame_npz)]
    if plumed_colvar_heavy_flush:
        cmd += ["--plumed-colvar-heavy-flush"]
    if platform in ("CUDA", "OpenCL") and openmm_device_index is not None:
        cmd += ["--openmm-device-index", str(int(openmm_device_index))]
    if log_gpu_util:
        cmd.append("--log-gpu-util")
        cmd += ["--gpu-util-interval", str(float(gpu_util_interval))]
    if gpu_util_out is not None:
        cmd += ["--gpu-util-out", str(gpu_util_out)]

    if bias_cv == "oneopes":
        if oneopes_axis_p0_boltz is not None:
            cmd += [
                "--oneopes-axis-p0-boltz",
                ",".join(str(int(x)) for x in oneopes_axis_p0_boltz),
            ]
        if oneopes_axis_p1_boltz is not None:
            cmd += [
                "--oneopes-axis-p1-boltz",
                ",".join(str(int(x)) for x in oneopes_axis_p1_boltz),
            ]
        if oneopes_contact_pairs_boltz is not None:
            pair_str = ",".join(f"{int(p)}-{int(l)}" for p, l in oneopes_contact_pairs_boltz)
            cmd += ["--oneopes-contact-pairs-boltz", pair_str]
        if oneopes_hydration_boltz is not None and len(oneopes_hydration_boltz) > 0:
            cmd += [
                "--oneopes-hydration-boltz",
                ",".join(str(int(x)) for x in oneopes_hydration_boltz),
            ]
        if oneopes_water_oxygen_plumed is not None and len(oneopes_water_oxygen_plumed) > 0:
            cmd += [
                "--oneopes-water-oxygen-plumed",
                ",".join(str(int(x)) for x in oneopes_water_oxygen_plumed),
            ]
        cmd += [
            "--oneopes-water-pace",
            str(int(oneopes_water_pace)),
            "--oneopes-water-barrier",
            str(float(oneopes_water_barrier)),
            "--oneopes-water-biasfactor",
            str(float(oneopes_water_biasfactor)),
            "--oneopes-water-sigma",
            str(float(oneopes_water_sigma)),
            "--oneopes-hydration-max-sites",
            str(int(oneopes_hydration_max_sites)),
            "--oneopes-hydration-min-density",
            str(float(oneopes_hydration_min_density)),
        ]
        if not oneopes_auto_hydration:
            cmd.append("--no-oneopes-auto-hydration")
        if not oneopes_hydration_use_3drism:
            cmd.append("--no-oneopes-hydration-use-3drism")

    print(f"  [md] Command: {' '.join(cmd)}", flush=True)
    result = subprocess.run(cmd, check=False, env=child_env_with_repo_src_python())
    if result.returncode != 0:
        raise RuntimeError(
            f"OpenMM OPES-MD failed with exit code {result.returncode}. "
            "See stderr above for details."
        )


def _run_openmm_oneopes_repex(
    *,
    topo_npz: Path,
    frame_npz: Path | None,
    mol_dir: Path,
    out_dir: Path,
    n_steps: int,
    save_every: int,
    deposit_pace: int,
    opes_barrier: float,
    opes_biasfactor: float,
    opes_sigma: str,
    temperature: float,
    pocket_radius: float,
    platform: str,
    minimize_steps: int,
    progress_every: int,
    save_opes_every: int,
    opes_mode: str,
    opes_kernel_cutoff: float | None,
    opes_nlist_parameters: tuple[float, float] | None,
    plumed_colvar_heavy_flush: bool,
    log_gpu_util: bool,
    gpu_util_interval: float,
    bias_cv: str,
    opes_explore: bool,
    opes_wall_dist: float | None,
    opes_wall_kappa: float,
    coordination_r0: float,
    opes_expanded_temp_max: float | None,
    opes_expanded_pace: int,
    oneopes_axis_p0_boltz: list[int] | None,
    oneopes_axis_p1_boltz: list[int] | None,
    oneopes_contact_pairs_boltz: list[tuple[int, int]] | None,
    oneopes_hydration_boltz: list[int] | None,
    oneopes_water_oxygen_plumed: list[int] | None,
    oneopes_water_pace: int,
    oneopes_water_barrier: float,
    oneopes_water_biasfactor: float,
    oneopes_water_sigma: float,
    oneopes_auto_hydration: bool,
    oneopes_hydration_max_sites: int,
    oneopes_hydration_use_3drism: bool,
    oneopes_hydration_min_density: float,
    n_replicas: int,
    oneopes_protocol: str,
    devices: str,
    replica_device_map: str,
    replica_devices: str | None,
    max_active_contexts_per_device: int,
    evaluator_placement: str,
    paper_oneopes_ligand_axis_p0_boltz: str | None,
    paper_oneopes_ligand_axis_p1_boltz: str | None,
    paper_oneopes_aux_guest_boltz: str | None,
) -> None:
    """Invoke the GPU-only OneOPES HREX driver via subprocess."""
    md_script = _REPO_ROOT / "scripts" / "run_openmm_oneopes_repex.py"
    cmd = [
        sys.executable, str(md_script),
        "--topo-npz", str(topo_npz),
        "--out", str(out_dir),
        "--n-steps", str(n_steps),
        "--save-every", str(save_every),
        "--deposit-pace", str(deposit_pace),
        "--opes-barrier", str(opes_barrier),
        "--opes-biasfactor", str(opes_biasfactor),
        "--opes-sigma", opes_sigma,
        "--temperature", str(temperature),
        "--pocket-radius", str(pocket_radius),
        "--platform", platform,
        "--minimize-steps", str(minimize_steps),
        "--progress-every", str(progress_every),
        "--save-opes-every", str(save_opes_every),
        "--opes-mode", opes_mode,
        "--mol-dir", str(mol_dir),
        "--bias-cv", str(bias_cv),
        "--n-replicas", str(int(n_replicas)),
        "--oneopes-protocol", str(oneopes_protocol),
        "--devices", str(devices),
        "--replica-device-map", str(replica_device_map),
        "--max-active-contexts-per-device", str(int(max_active_contexts_per_device)),
        "--evaluator-placement", str(evaluator_placement),
    ]
    if replica_devices is not None:
        cmd += ["--replica-devices", replica_devices]
    if opes_explore:
        cmd.append("--opes-explore")
    if opes_wall_dist is not None:
        cmd += ["--opes-wall-dist", str(float(opes_wall_dist))]
        cmd += ["--opes-wall-kappa", str(float(opes_wall_kappa))]
    cmd += ["--coordination-r0", str(float(coordination_r0))]
    if opes_expanded_temp_max is not None:
        cmd += [
            "--opes-expanded-temp-max",
            str(float(opes_expanded_temp_max)),
            "--opes-expanded-pace",
            str(int(opes_expanded_pace)),
        ]
    if opes_kernel_cutoff is not None:
        cmd += ["--opes-kernel-cutoff", str(opes_kernel_cutoff)]
    if opes_nlist_parameters is not None:
        a, b = opes_nlist_parameters
        cmd += ["--opes-nlist-parameters", f"{a},{b}"]
    if frame_npz is not None:
        cmd += ["--frame-npz", str(frame_npz)]
    if plumed_colvar_heavy_flush:
        cmd += ["--plumed-colvar-heavy-flush"]
    if log_gpu_util:
        cmd.append("--log-gpu-util")
        cmd += ["--gpu-util-interval", str(float(gpu_util_interval))]

    if oneopes_axis_p0_boltz is not None:
        cmd += [
            "--oneopes-axis-p0-boltz",
            ",".join(str(int(x)) for x in oneopes_axis_p0_boltz),
        ]
    if oneopes_axis_p1_boltz is not None:
        cmd += [
            "--oneopes-axis-p1-boltz",
            ",".join(str(int(x)) for x in oneopes_axis_p1_boltz),
        ]
    if oneopes_contact_pairs_boltz is not None:
        pair_str = ",".join(f"{int(p)}-{int(l)}" for p, l in oneopes_contact_pairs_boltz)
        cmd += ["--oneopes-contact-pairs-boltz", pair_str]
    if oneopes_hydration_boltz is not None and len(oneopes_hydration_boltz) > 0:
        cmd += [
            "--oneopes-hydration-boltz",
            ",".join(str(int(x)) for x in oneopes_hydration_boltz),
        ]
    if oneopes_water_oxygen_plumed is not None and len(oneopes_water_oxygen_plumed) > 0:
        cmd += [
            "--oneopes-water-oxygen-plumed",
            ",".join(str(int(x)) for x in oneopes_water_oxygen_plumed),
        ]
    cmd += [
        "--oneopes-water-pace",
        str(int(oneopes_water_pace)),
        "--oneopes-water-barrier",
        str(float(oneopes_water_barrier)),
        "--oneopes-water-biasfactor",
        str(float(oneopes_water_biasfactor)),
        "--oneopes-water-sigma",
        str(float(oneopes_water_sigma)),
        "--oneopes-hydration-max-sites",
        str(int(oneopes_hydration_max_sites)),
        "--oneopes-hydration-min-density",
        str(float(oneopes_hydration_min_density)),
    ]
    if not oneopes_auto_hydration:
        cmd.append("--no-oneopes-auto-hydration")
    if not oneopes_hydration_use_3drism:
        cmd.append("--no-oneopes-hydration-use-3drism")

    if str(oneopes_protocol).replace("-", "_") == "paper_host_guest":
        if paper_oneopes_ligand_axis_p0_boltz is None:
            raise RuntimeError("--paper-oneopes-ligand-axis-p0-boltz is required for paper OneOPES REPEX.")
        if paper_oneopes_ligand_axis_p1_boltz is None:
            raise RuntimeError("--paper-oneopes-ligand-axis-p1-boltz is required for paper OneOPES REPEX.")
        if paper_oneopes_aux_guest_boltz is None:
            raise RuntimeError("--paper-oneopes-aux-guest-boltz is required for paper OneOPES REPEX.")
        cmd += [
            "--paper-oneopes-ligand-axis-p0-boltz",
            paper_oneopes_ligand_axis_p0_boltz,
            "--paper-oneopes-ligand-axis-p1-boltz",
            paper_oneopes_ligand_axis_p1_boltz,
            "--paper-oneopes-aux-guest-boltz",
            paper_oneopes_aux_guest_boltz,
        ]

    print(f"  [md] Command: {' '.join(cmd)}", flush=True)
    result = subprocess.run(cmd, check=False, env=child_env_with_repo_src_python())
    if result.returncode != 0:
        raise RuntimeError(
            f"OpenMM OneOPES REPEX failed with exit code {result.returncode}. "
            "See stderr above for details."
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Stage 0: Run OpenMM OPES-MD reference simulations for all 3 diagnostic systems.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--out", type=Path, default=Path("outputs/campaign"),
                        help="Root campaign output directory.")
    parser.add_argument(
        "--cache",
        type=Path,
        default=None,
        help=(
            "Boltz model cache directory (checkpoints, mols/). "
            "If omitted, uses ``BOLTZ_CACHE`` or ``SCRATCH/.boltz`` (same rules as "
            "other campaign scripts — no home-directory default). "
            "Set SCRATCH or BOLTZ_CACHE for cluster scratch storage."
        ),
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda",
        help="PyTorch device for Boltz: cpu, cuda, or cuda:N (default: cuda). "
        "Use cpu only for debugging or CI; structure sampling is very slow.",
    )
    parser.add_argument(
        "--init-sampling-steps",
        type=int,
        default=200,
        help="Boltz-2 structure diffusion sampling steps (model ``sampling_steps``; "
        "official boltz CLI default is 200, see boltz docs/prediction.md).",
    )
    parser.add_argument(
        "--recycling-steps",
        type=int,
        default=3,
        help="Boltz-2 trunk recycling iterations (official boltz CLI default is 3).",
    )
    parser.add_argument("--cases", type=str, default="1,2,3",
                        help="Comma-separated case numbers to run (1, 2, or 3).")

    # MD hyperparameters
    parser.add_argument("--n-steps", type=int, default=5_000_000,
                        help="Total MD steps per system (5M = 10 ns at 2 fs).")
    parser.add_argument("--save-every", type=int, default=1000,
                        help="Save a structure shard every N steps.")
    parser.add_argument("--deposit-pace", type=int, default=500,
                        help="OPES kernel deposit frequency (steps).")
    parser.add_argument(
        "--opes-barrier",
        type=float,
        default=40.0,
        help="OPES BARRIER in kJ/mol (forwarded to the MD runner).",
    )
    parser.add_argument("--opes-biasfactor", type=float, default=10.0)
    parser.add_argument(
        "--opes-sigma",
        type=str,
        default="0.3,0.5,1.0",
        help="Per-CV kernel sigmas (Å): three values for default --bias-cv 3d; two for 2d.",
    )
    parser.add_argument(
        "--bias-cv",
        type=str,
        default="3d",
        choices=["2d", "3d", "oneopes"],
        help=(
            "Forwarded: PLUMED CV set (default 3d: lig_rmsd+lig_dist+lig_contacts; "
            "2d drops coordination; oneopes = PROJECTION_ON_AXIS + CONTACTMAP, "
            "requires --opes-mode plumed)."
        ),
    )
    parser.add_argument(
        "--oneopes-repex",
        action="store_true",
        help=(
            "Run Stage 00 through scripts/run_openmm_oneopes_repex.py instead of the "
            "single-replica OPES-MD driver. Requires --bias-cv oneopes and a GPU platform."
        ),
    )
    parser.add_argument(
        "--repex-n-replicas",
        type=int,
        default=8,
        help="Replica count (2–8) forwarded to the OneOPES REPEX driver.",
    )
    parser.add_argument(
        "--oneopes-protocol",
        type=str,
        default="paper-host-guest",
        choices=["legacy-boltz", "paper-host-guest"],
        help="OneOPES REPEX protocol forwarded to the replica-exchange driver.",
    )
    parser.add_argument(
        "--devices",
        type=str,
        default="0,1",
        help="Comma-separated OpenMM GPU ordinals for OneOPES REPEX, e.g. '0,1'.",
    )
    parser.add_argument(
        "--replica-device-map",
        type=str,
        default="round-robin",
        choices=["round-robin", "packed", "explicit"],
        help="Replica-to-GPU placement policy for OneOPES REPEX.",
    )
    parser.add_argument(
        "--replica-devices",
        type=str,
        default=None,
        help="Explicit comma-separated replica device list when --replica-device-map explicit.",
    )
    parser.add_argument(
        "--max-active-contexts-per-device",
        type=int,
        default=4,
        help="Maximum active OpenMM contexts per GPU accepted by the REPEX driver.",
    )
    parser.add_argument(
        "--evaluator-placement",
        type=str,
        default="same-device",
        choices=["same-device", "dedicated", "serial"],
        help="Cross-Hamiltonian evaluator placement policy for OneOPES REPEX.",
    )
    parser.add_argument(
        "--paper-oneopes-ligand-axis-p0-boltz",
        type=str,
        default=None,
        help="Paper OneOPES: comma-separated Boltz indices for one ligand-axis anchor.",
    )
    parser.add_argument(
        "--paper-oneopes-ligand-axis-p1-boltz",
        type=str,
        default=None,
        help="Paper OneOPES: comma-separated Boltz indices for the other ligand-axis anchor.",
    )
    parser.add_argument(
        "--paper-oneopes-aux-guest-boltz",
        type=str,
        default=None,
        help="Paper OneOPES: seven comma-separated guest Boltz indices in L4,V6,L1,V8,V4,V10,V2 order.",
    )
    parser.add_argument(
        "--opes-bias-style",
        type=str,
        default="explore",
        choices=["explore", "metad"],
        help=(
            "Forwarded: 'explore' uses OPES_METAD_EXPLORE (default); "
            "'metad' uses OPES_METAD."
        ),
    )
    parser.add_argument(
        "--opes-wall-dist",
        type=float,
        default=None,
        metavar="ANGSTROM",
        help=(
            "Forwarded: UPPER_WALLS on lig_dist (Å). If omitted, the MD runner sets "
            "the wall adaptively from the initial ligand–pocket distance + 10 Å."
        ),
    )
    parser.add_argument(
        "--opes-wall-kappa",
        type=float,
        default=200.0,
        help="Forwarded: UPPER_WALLS KAPPA when --opes-wall-dist is set.",
    )
    parser.add_argument(
        "--coordination-r0",
        type=float,
        default=4.5,
        help="Forwarded: COORDINATION R_0 (Å) for lig_contacts in 3d mode.",
    )
    parser.add_argument(
        "--oneopes-axis-p0-boltz",
        type=_parse_comma_int_list,
        default=None,
        help="Forwarded (--bias-cv oneopes): pocket-deep anchor Boltz indices.",
    )
    parser.add_argument(
        "--oneopes-axis-p1-boltz",
        type=_parse_comma_int_list,
        default=None,
        help="Forwarded (--bias-cv oneopes): pocket-mouth anchor Boltz indices.",
    )
    parser.add_argument(
        "--oneopes-contact-pairs-boltz",
        type=_parse_oneopes_contact_pairs_boltz,
        default=None,
        help="Forwarded: CONTACTMAP pairs as prot-lig,prot-lig (Boltz global indices).",
    )
    parser.add_argument(
        "--oneopes-hydration-boltz",
        type=_parse_comma_int_list,
        default=None,
        help="Forwarded: optional hydration-site Boltz indices for auxiliary water OPES.",
    )
    parser.add_argument(
        "--oneopes-water-oxygen-plumed",
        type=_parse_comma_int_list,
        default=None,
        help="Forwarded: optional PLUMED 1-based water oxygen list for WO GROUP.",
    )
    parser.add_argument("--oneopes-water-pace", type=int, default=40_000)
    parser.add_argument("--oneopes-water-barrier", type=float, default=3.0)
    parser.add_argument("--oneopes-water-biasfactor", type=float, default=5.0)
    parser.add_argument("--oneopes-water-sigma", type=float, default=0.15)
    parser.add_argument(
        "--oneopes-auto-hydration",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Forwarded (--bias-cv oneopes): infer hydration spots when list omitted.",
    )
    parser.add_argument(
        "--oneopes-hydration-max-sites",
        type=int,
        default=5,
        help="Forwarded: cap on auto-inferred hydration spots.",
    )
    parser.add_argument(
        "--oneopes-hydration-use-3drism",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Forwarded: try 3D-RISM blob picking before geometric fallback.",
    )
    parser.add_argument(
        "--oneopes-hydration-min-density",
        type=float,
        default=0.5,
        help="Forwarded: metatwist --threshold for RISM blob picking.",
    )
    parser.add_argument("--temperature", type=float, default=300.0,
                        help="Langevin temperature (K).")
    parser.add_argument("--pocket-radius", type=float, default=6.0,
                        help="Pocket definition radius around ligand (Angstrom).")
    parser.add_argument(
        "--platform",
        type=str,
        default="CUDA",
        choices=["CUDA", "OpenCL", "CPU"],
        help="OpenMM platform (default: CUDA). CPU/OpenCL are fallbacks for "
        "machines without CUDA or for local debugging.",
    )
    parser.add_argument(
        "--openmm-device-index",
        type=int,
        default=None,
        metavar="N",
        help=(
            "OpenMM CUDA/OpenCL DeviceIndex. Default: same ordinal as --device "
            "for cuda:N (or 0 for bare cuda). Ignored when --platform is CPU."
        ),
    )
    parser.add_argument("--minimize-steps", type=int, default=1000,
                        help="Energy minimisation steps before MD.")
    parser.add_argument("--progress-every", type=int, default=10_000)
    parser.add_argument("--save-opes-every", type=int, default=50_000)
    parser.add_argument(
        "--opes-kernel-cutoff",
        type=float,
        default=None,
        metavar="SIGMA",
        help=(
            "Forwarded to the MD runner: PLUMED OPES_METAD KERNEL_CUTOFF. "
            "Omit for auto max(3.5, PLUMED default formula)."
        ),
    )
    parser.add_argument(
        "--opes-nlist-parameters",
        type=_parse_opes_nlist_parameters,
        default=None,
        metavar="A,B",
        help="Forwarded to the MD runner: OPES NLIST_PARAMETERS, e.g. '4.0,0.4'.",
    )
    parser.add_argument(
        "--opes-expanded-temp-max",
        type=float,
        default=None,
        metavar="K",
        help=(
            "Forwarded to the MD runner: if set, add PLUMED OPES_EXPANDED + "
            "ECV_MULTITHERMAL (TEMP_MAX=K Kelvin; must exceed --temperature). "
            "Requires --opes-mode plumed."
        ),
    )
    parser.add_argument(
        "--opes-expanded-pace",
        type=int,
        default=50,
        help="Forwarded to the MD runner: OPES_EXPANDED PACE (MD steps) when expanded is enabled.",
    )
    parser.add_argument(
        "--plumed-colvar-heavy-flush",
        action="store_true",
        help=(
            "Forwarded to the MD runner: emit PRINT ... HEAVY_FLUSH for COLVAR. "
            "Use after rebuilding PLUMED from the patched plumed2 submodule "
            "(scripts/build_plumed_opes.sh)."
        ),
    )
    parser.add_argument(
        "--log-gpu-util",
        action="store_true",
        help=(
            "Forwarded to the MD runner: sample nvidia-smi in a background thread "
            "during MD (CUDA/OpenCL only; requires nvidia-smi on PATH)."
        ),
    )
    parser.add_argument(
        "--gpu-util-interval",
        type=float,
        default=0.1,
        metavar="SEC",
        help="Forwarded with --log-gpu-util: seconds between GPU samples.",
    )
    parser.add_argument(
        "--gpu-util-out",
        type=Path,
        default=None,
        metavar="CSV",
        help="Forwarded with --log-gpu-util: output CSV path (default: <md-out>/gpu_utilization.csv).",
    )
    parser.add_argument(
        "--opes-mode",
        type=str,
        default="plumed",
        choices=["plumed", "observer"],
        help=(
            "OPES mode for the OpenMM MD runner. 'plumed' uses PLUMED OPES_METAD / "
            "OPES_METAD_EXPLORE (see --opes-bias-style; needs PLUMED built with "
            "--enable-modules=opes; stock conda-forge plumed lacks this — use a "
            "custom kernel or --opes-mode observer). "
            "'observer' is unbiased MD with Python OPESBias logging only."
        ),
    )
    parser.add_argument("--resume", action="store_true",
                        help="If final OPES outputs already exist, skip that system.")
    args = parser.parse_args()

    n_sigma = len([p for p in args.opes_sigma.split(",") if p.strip()])
    if args.bias_cv == "2d" and n_sigma != 2:
        parser.error("--bias-cv 2d requires exactly two comma-separated values in --opes-sigma")
    if args.bias_cv == "3d" and n_sigma != 3:
        parser.error("--bias-cv 3d requires exactly three comma-separated values in --opes-sigma")
    if args.bias_cv == "oneopes" and n_sigma != 2:
        parser.error("--bias-cv oneopes requires exactly two comma-separated values in --opes-sigma")
    if args.bias_cv == "oneopes" and args.opes_mode != "plumed":
        parser.error("--bias-cv oneopes requires --opes-mode plumed")
    if args.oneopes_repex:
        if args.bias_cv != "oneopes":
            parser.error("--oneopes-repex requires --bias-cv oneopes")
        if args.platform == "CPU":
            parser.error("--oneopes-repex requires --platform CUDA or OpenCL")
        if int(args.repex_n_replicas) < 2 or int(args.repex_n_replicas) > 8:
            parser.error("--repex-n-replicas must be in 2..8 for --oneopes-repex")
        if args.oneopes_protocol == "paper-host-guest" and int(args.repex_n_replicas) != 8:
            parser.error("--oneopes-protocol paper-host-guest requires --repex-n-replicas 8")
        if args.oneopes_protocol == "paper-host-guest":
            if args.paper_oneopes_ligand_axis_p0_boltz is None:
                parser.error("--oneopes-repex paper-host-guest requires --paper-oneopes-ligand-axis-p0-boltz")
            if args.paper_oneopes_ligand_axis_p1_boltz is None:
                parser.error("--oneopes-repex paper-host-guest requires --paper-oneopes-ligand-axis-p1-boltz")
            if args.paper_oneopes_aux_guest_boltz is None:
                parser.error("--oneopes-repex paper-host-guest requires --paper-oneopes-aux-guest-boltz")
    if int(args.oneopes_hydration_max_sites) < 1:
        parser.error("--oneopes-hydration-max-sites must be >= 1")

    if args.opes_expanded_temp_max is not None:
        if args.opes_mode != "plumed":
            parser.error("--opes-expanded-temp-max requires --opes-mode plumed")
        if float(args.opes_expanded_temp_max) <= float(args.temperature):
            parser.error(
                "--opes-expanded-temp-max must be strictly greater than --temperature"
            )

    if torch.cuda.is_available():
        _torch_dev = parse_torch_device(args.device)
        maybe_set_torch_cuda_current_device(_torch_dev)
        device_str = str(_torch_dev)
    else:
        _torch_dev = torch.device("cpu")
        device_str = "cpu"
    openmm_gpu_index = (
        args.openmm_device_index
        if args.openmm_device_index is not None
        else cuda_device_index_for_openmm(_torch_dev)
    )

    if args.opes_mode == "plumed":
        from genai_tps.simulation.plumed_kernel import assert_plumed_opes_metad_available

        assert_plumed_opes_metad_available()

    cache = (
        Path(args.cache).expanduser().resolve()
        if args.cache is not None
        else default_boltz_cache_dir()
    )
    out_root = args.out.expanduser().resolve()
    out_root.mkdir(parents=True, exist_ok=True)

    selected_cases = {int(c.strip()) for c in args.cases.split(",")}

    campaign_log = []

    for idx, sys_def in enumerate(_SYSTEMS, start=1):
        if idx not in selected_cases:
            print(f"\n[00] Skipping {sys_def['name']} (not in --cases {args.cases})")
            continue

        print(f"\n{'='*60}")
        print(f"  System {idx}/3: {sys_def['description']}")
        print(f"{'='*60}", flush=True)

        run_subdir = "openmm_oneopes_repex" if args.oneopes_repex else "openmm_opes_md"
        system_out = out_root / sys_def["name"] / run_subdir
        system_out.mkdir(parents=True, exist_ok=True)

        # Check for existing OPES state (resume logic)
        final_state = (
            system_out / "exchange_log.csv"
            if args.oneopes_repex
            else (
            system_out / "opes_states" / "STATE"
            if args.opes_mode == "plumed"
            else system_out / "opes_state_final.json"
            )
        )
        if args.resume and final_state.is_file():
            print(f"  [00] Found existing OPES state at {final_state}; skipping.", flush=True)
            campaign_log.append({"case": sys_def["name"], "status": "skipped_resume"})
            continue

        yaml_path = _REPO_ROOT / sys_def["yaml"]
        if not yaml_path.is_file():
            raise FileNotFoundError(f"YAML input not found: {yaml_path}")

        # Step 1: Boltz preprocessing + one-shot structure sample for initial coords
        print(f"  [00] Boltz preprocessing and initial coordinates...", flush=True)
        bundle, topo_npz = _boltz_prep_for_openmm(
            yaml_path,
            system_out,
            cache,
            device_str,
            init_sampling_steps=args.init_sampling_steps,
            recycling_steps=args.recycling_steps,
        )
        from genai_tps.backends.boltz.inference import predict_sample_atom_coords_numpy

        print(
            f"  [00] Boltz-2 predict (sampling_steps={args.init_sampling_steps}, "
            f"recycling_steps={args.recycling_steps}) for MD initial pose...",
            flush=True,
        )
        init_coords = predict_sample_atom_coords_numpy(bundle)
        del bundle
        try:
            torch.cuda.empty_cache()
        except Exception:
            pass

        frame_npz = system_out / "boltz_init_coords.npz"
        np.savez_compressed(frame_npz, coords=init_coords)
        print(f"  [prep] Initial coords NPZ: {frame_npz} ({init_coords.shape[0]} atoms)", flush=True)

        # Step 2: Run OpenMM OPES-MD
        opes_restart = None
        restart_path = (
            system_out / "opes_states" / "STATE"
            if args.opes_mode == "plumed"
            else system_out / "opes_states" / "opes_state_latest.json"
        )
        if args.resume and restart_path.is_file():
            opes_restart = restart_path
            print(f"  [00] Resuming OPES from {opes_restart}", flush=True)

        if args.oneopes_repex:
            print(
                f"  [00] Running OpenMM OneOPES REPEX "
                f"({args.repex_n_replicas} replicas, {args.n_steps:,} steps, GPUs {args.devices})...",
                flush=True,
            )
            _run_openmm_oneopes_repex(
                topo_npz=topo_npz,
                frame_npz=frame_npz,
                mol_dir=cache / "mols",
                out_dir=system_out,
                n_steps=args.n_steps,
                save_every=args.save_every,
                deposit_pace=args.deposit_pace,
                opes_barrier=args.opes_barrier,
                opes_biasfactor=args.opes_biasfactor,
                opes_sigma=args.opes_sigma,
                temperature=args.temperature,
                pocket_radius=args.pocket_radius,
                platform=args.platform,
                minimize_steps=args.minimize_steps,
                progress_every=args.progress_every,
                save_opes_every=args.save_opes_every,
                opes_mode=args.opes_mode,
                opes_kernel_cutoff=args.opes_kernel_cutoff,
                opes_nlist_parameters=args.opes_nlist_parameters,
                plumed_colvar_heavy_flush=bool(args.plumed_colvar_heavy_flush),
                log_gpu_util=bool(args.log_gpu_util),
                gpu_util_interval=float(args.gpu_util_interval),
                bias_cv=str(args.bias_cv),
                opes_explore=(str(args.opes_bias_style) == "explore"),
                opes_wall_dist=args.opes_wall_dist,
                opes_wall_kappa=float(args.opes_wall_kappa),
                coordination_r0=float(args.coordination_r0),
                opes_expanded_temp_max=args.opes_expanded_temp_max,
                opes_expanded_pace=int(args.opes_expanded_pace),
                oneopes_axis_p0_boltz=args.oneopes_axis_p0_boltz,
                oneopes_axis_p1_boltz=args.oneopes_axis_p1_boltz,
                oneopes_contact_pairs_boltz=args.oneopes_contact_pairs_boltz,
                oneopes_hydration_boltz=args.oneopes_hydration_boltz,
                oneopes_water_oxygen_plumed=args.oneopes_water_oxygen_plumed,
                oneopes_water_pace=int(args.oneopes_water_pace),
                oneopes_water_barrier=float(args.oneopes_water_barrier),
                oneopes_water_biasfactor=float(args.oneopes_water_biasfactor),
                oneopes_water_sigma=float(args.oneopes_water_sigma),
                oneopes_auto_hydration=bool(args.oneopes_auto_hydration),
                oneopes_hydration_max_sites=int(args.oneopes_hydration_max_sites),
                oneopes_hydration_use_3drism=bool(args.oneopes_hydration_use_3drism),
                oneopes_hydration_min_density=float(args.oneopes_hydration_min_density),
                n_replicas=int(args.repex_n_replicas),
                oneopes_protocol=str(args.oneopes_protocol),
                devices=str(args.devices),
                replica_device_map=str(args.replica_device_map),
                replica_devices=args.replica_devices,
                max_active_contexts_per_device=int(args.max_active_contexts_per_device),
                evaluator_placement=str(args.evaluator_placement),
                paper_oneopes_ligand_axis_p0_boltz=args.paper_oneopes_ligand_axis_p0_boltz,
                paper_oneopes_ligand_axis_p1_boltz=args.paper_oneopes_ligand_axis_p1_boltz,
                paper_oneopes_aux_guest_boltz=args.paper_oneopes_aux_guest_boltz,
            )
        else:
            print(f"  [00] Running OpenMM OPES-MD ({args.n_steps:,} steps)...", flush=True)
            _run_openmm_md(
                topo_npz=topo_npz,
                frame_npz=frame_npz,
                mol_dir=cache / "mols",
                out_dir=system_out,
                n_steps=args.n_steps,
                save_every=args.save_every,
                deposit_pace=args.deposit_pace,
                opes_barrier=args.opes_barrier,
                opes_biasfactor=args.opes_biasfactor,
                opes_sigma=args.opes_sigma,
                temperature=args.temperature,
                pocket_radius=args.pocket_radius,
                platform=args.platform,
                minimize_steps=args.minimize_steps,
                progress_every=args.progress_every,
                save_opes_every=args.save_opes_every,
                opes_restart=opes_restart,
                opes_mode=args.opes_mode,
                opes_kernel_cutoff=args.opes_kernel_cutoff,
                opes_nlist_parameters=args.opes_nlist_parameters,
                plumed_colvar_heavy_flush=bool(args.plumed_colvar_heavy_flush),
                openmm_device_index=openmm_gpu_index,
                log_gpu_util=bool(args.log_gpu_util),
                gpu_util_interval=float(args.gpu_util_interval),
                gpu_util_out=(
                    args.gpu_util_out.expanduser().resolve()
                    if args.gpu_util_out is not None
                    else None
                ),
                bias_cv=str(args.bias_cv),
                opes_explore=(str(args.opes_bias_style) == "explore"),
                opes_wall_dist=args.opes_wall_dist,
                opes_wall_kappa=float(args.opes_wall_kappa),
                coordination_r0=float(args.coordination_r0),
                opes_expanded_temp_max=args.opes_expanded_temp_max,
                opes_expanded_pace=int(args.opes_expanded_pace),
                oneopes_axis_p0_boltz=args.oneopes_axis_p0_boltz,
                oneopes_axis_p1_boltz=args.oneopes_axis_p1_boltz,
                oneopes_contact_pairs_boltz=args.oneopes_contact_pairs_boltz,
                oneopes_hydration_boltz=args.oneopes_hydration_boltz,
                oneopes_water_oxygen_plumed=args.oneopes_water_oxygen_plumed,
                oneopes_water_pace=int(args.oneopes_water_pace),
                oneopes_water_barrier=float(args.oneopes_water_barrier),
                oneopes_water_biasfactor=float(args.oneopes_water_biasfactor),
                oneopes_water_sigma=float(args.oneopes_water_sigma),
                oneopes_auto_hydration=bool(args.oneopes_auto_hydration),
                oneopes_hydration_max_sites=int(args.oneopes_hydration_max_sites),
                oneopes_hydration_use_3drism=bool(args.oneopes_hydration_use_3drism),
                oneopes_hydration_min_density=float(args.oneopes_hydration_min_density),
            )

        # Count output shards
        if args.oneopes_repex:
            shard_count = sum(
                len(list(rep_dir.glob("wdsm_samples/wdsm_step_*.npz")))
                for rep_dir in system_out.glob("rep[0-9][0-9][0-9]")
            )
        else:
            shard_count = len(list((system_out / "wdsm_samples").glob("wdsm_step_*.npz")))
        print(f"  [00] Done. {shard_count} shards written to {system_out / 'wdsm_samples'}", flush=True)
        campaign_log.append({
            "case": sys_def["name"],
            "status": "complete",
            "n_shards": shard_count,
            "out_dir": str(system_out),
            "topo_npz": str(topo_npz),
            "frame_npz": str(frame_npz),
        })

    log_path = out_root / "00_reference_data_log.json"
    _write_merged_campaign_log(out_root, campaign_log)
    print(f"\n[00] Campaign log (merged): {log_path}", flush=True)
    print("[00] Stage 0 complete. Run 01_assemble_datasets.py next.", flush=True)


if __name__ == "__main__":
    main()
