#!/usr/bin/env python3
"""Stage 0 — Run OpenMM OPES-MD for all three diagnostic systems.

Ground-truth reference data MUST come from independent physical simulations.
This script drives ``genai_tps.simulation.openmm_md_runner`` (AMBER14 + GBn2
implicit solvent, Langevin 300 K, 2 fs timestep, real PLUMED OPES_METAD bias
forces on ligand-pose RMSD and ligand-pocket distance) for each of the three
diagnostic systems defined in ``inputs/tps_diagnostic/``.

Boltz ``processed/structures/*.npz`` files supply **topology** (atom ordering for
the OpenMM bridge) but typically contain **placeholder coordinates**.  After
preprocessing, this script runs one Boltz-2 diffusion sample to produce a
self-consistent 3D pose, saves it to ``boltz_init_coords.npz``, and passes that
file as ``--frame-npz`` to the MD runner.  Default sampling and recycling match
the official ``boltz predict`` CLI (``docs/prediction.md`` on the Boltz repo):
``--sampling_steps 200``, ``--recycling_steps 3``.  The resulting OpenMM
trajectory remains an AMBER + implicit-solvent reference independent of any TPS
checkpoints.

Why OpenMM, not TPS trajectories?
    TPS trajectories are generated by the Boltz-2 model being evaluated.
    Using them as training data would be circular.  OpenMM MD with an explicit
    force field (AMBER14) provides a model-independent physical reference that
    obeys the Boltzmann distribution for a known energy function.

Pipeline role:
    00_generate_reference_data  →  01_assemble_datasets  →  02_finetune_boltz2

Outputs (one subdirectory per system)::

    outputs/campaign/case{1,2,3}/openmm_opes_md/
        wdsm_samples/wdsm_step_*.npz   # per-frame coordinate + logw shards
        cv_log.json                    # step / cv / logw time series
        opes_states/COLVAR             # PLUMED CV / bias time series
        opes_states/KERNELS            # OPES kernel history
        opes_states/STATE              # periodic compressed OPES state
        plumed_opes.dat                # PLUMED input deck used by OpenMM
        md_summary.json                # timing and hyperparameter record

Example::

    # Quick test (100 k MD steps per system; Boltz + OpenMM default to GPU):
    python scripts/campaign/00_generate_reference_data.py \
        --n-steps 100000 --out outputs/campaign

    # Production (5 M MD steps):
    python scripts/campaign/00_generate_reference_data.py \
        --n-steps 5000000 --out outputs/campaign

    CPU-only fallback (CI or machines without a GPU; very slow for Boltz):
    ``--device cpu --platform CPU``.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT / "src" / "python") not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT / "src" / "python"))

from genai_tps.simulation.openmm_md_runner import _parse_opes_nlist_parameters
from genai_tps.subprocess_support import child_env_with_repo_src_python

# ---------------------------------------------------------------------------
# System definitions — one entry per diagnostic case
# ---------------------------------------------------------------------------

_SYSTEMS = [
    {
        "name": "case1_mek1_fzc_novel",
        "yaml": "inputs/tps_diagnostic/case1_mek1_fzc_novel.yaml",
        "cif": "inputs/tps_diagnostic/reference_structures/7XLP.cif",
        "ligand_ccd": "FZC",
        "description": "Case 1 — MEK1+FZC novel (negative control)",
    },
    {
        "name": "case2_cdk2_atp_wildtype",
        "yaml": "inputs/tps_diagnostic/case2_cdk2_atp_wildtype.yaml",
        "cif": "inputs/tps_diagnostic/reference_structures/1B38.cif",
        "ligand_ccd": "ATP",
        "description": "Case 2 — CDK2+ATP WT memorised (positive control)",
    },
    {
        "name": "case3_cdk2_atp_packed",
        "yaml": "inputs/tps_diagnostic/case3_cdk2_atp_packed.yaml",
        "cif": "inputs/tps_diagnostic/reference_structures/1B38.cif",
        "ligand_ccd": "ATP",
        "description": "Case 3 — CDK2+ATP Phe-packed adversarial",
    },
]


def _boltz_prep_for_openmm(
    yaml_path: Path,
    out_dir: Path,
    cache: Path,
    device: str,
    *,
    init_sampling_steps: int,
    recycling_steps: int,
):
    """Preprocess inputs, load Boltz-2, and return a bundle plus topology NPZ path.

    The processed ``structures/*.npz`` defines OpenMM–Boltz atom ordering but
    often has placeholder (zero) coordinates.  Call
    :func:`~genai_tps.backends.boltz.inference.predict_sample_atom_coords_numpy`
    on the returned bundle to obtain a self-consistent 3D pose for MD.
    """
    import torch

    from genai_tps.backends.boltz.inference import build_boltz_inference_session

    prep_dir = out_dir / "boltz_prep"
    bundle = build_boltz_inference_session(
        yaml_path=yaml_path,
        cache=cache,
        boltz_prep_dir=prep_dir,
        device=torch.device(device),
        diffusion_steps=int(init_sampling_steps),
        recycling_steps=int(recycling_steps),
        kernels=False,
    )
    topo_npz = bundle.topo_npz
    if topo_npz is None or not topo_npz.is_file():
        raise RuntimeError(
            f"Boltz preprocessing produced no topology NPZ under {prep_dir}. "
            "Check that the YAML and Boltz cache are correct."
        )
    print(f"  [prep] Topology NPZ: {topo_npz}", flush=True)
    return bundle, topo_npz


def _run_openmm_md(
    *,
    topo_npz: Path,
    frame_npz: Path | None,
    mol_dir: Path,
    out_dir: Path,
    n_steps: int,
    save_every: int,
    deposit_pace: int,
    opes_barrier: float,
    opes_biasfactor: float,
    opes_sigma: str,
    temperature: float,
    pocket_radius: float,
    platform: str,
    minimize_steps: int,
    progress_every: int,
    save_opes_every: int,
    opes_restart: Path | None,
    opes_mode: str,
    opes_kernel_cutoff: float | None,
    opes_nlist_parameters: tuple[float, float] | None,
) -> None:
    """Invoke the OpenMM OPES-MD runner via subprocess for isolation."""
    md_script = _REPO_ROOT / "scripts" / "run_openmm_opes_md.py"
    cmd = [
        sys.executable, str(md_script),
        "--topo-npz", str(topo_npz),
        "--out", str(out_dir),
        "--n-steps", str(n_steps),
        "--save-every", str(save_every),
        "--deposit-pace", str(deposit_pace),
        "--opes-barrier", str(opes_barrier),
        "--opes-biasfactor", str(opes_biasfactor),
        "--opes-sigma", opes_sigma,
        "--temperature", str(temperature),
        "--pocket-radius", str(pocket_radius),
        "--platform", platform,
        "--minimize-steps", str(minimize_steps),
        "--progress-every", str(progress_every),
        "--save-opes-every", str(save_opes_every),
        "--opes-mode", opes_mode,
        "--mol-dir", str(mol_dir),
    ]
    if opes_restart is not None:
        cmd += ["--opes-restart", str(opes_restart)]
    if opes_kernel_cutoff is not None:
        cmd += ["--opes-kernel-cutoff", str(opes_kernel_cutoff)]
    if opes_nlist_parameters is not None:
        a, b = opes_nlist_parameters
        cmd += ["--opes-nlist-parameters", f"{a},{b}"]
    if frame_npz is not None:
        cmd += ["--frame-npz", str(frame_npz)]

    print(f"  [md] Command: {' '.join(cmd)}", flush=True)
    result = subprocess.run(cmd, check=False, env=child_env_with_repo_src_python())
    if result.returncode != 0:
        raise RuntimeError(
            f"OpenMM OPES-MD failed with exit code {result.returncode}. "
            "See stderr above for details."
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Stage 0: Run OpenMM OPES-MD reference simulations for all 3 diagnostic systems.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--out", type=Path, default=Path("outputs/campaign"),
                        help="Root campaign output directory.")
    parser.add_argument("--cache", type=Path, default=None,
                        help="Boltz model cache directory (default: ~/.boltz).")
    parser.add_argument(
        "--device",
        type=str,
        default="cuda",
        help="PyTorch device for Boltz (default: cuda). Use ``cpu`` only for "
        "debugging or CI without a GPU; structure sampling is impractically slow.",
    )
    parser.add_argument(
        "--init-sampling-steps",
        type=int,
        default=200,
        help="Boltz-2 structure diffusion sampling steps (model ``sampling_steps``; "
        "official boltz CLI default is 200, see boltz docs/prediction.md).",
    )
    parser.add_argument(
        "--recycling-steps",
        type=int,
        default=3,
        help="Boltz-2 trunk recycling iterations (official boltz CLI default is 3).",
    )
    parser.add_argument("--cases", type=str, default="1,2,3",
                        help="Comma-separated case numbers to run (1, 2, or 3).")

    # MD hyperparameters
    parser.add_argument("--n-steps", type=int, default=5_000_000,
                        help="Total MD steps per system (5M = 10 ns at 2 fs).")
    parser.add_argument("--save-every", type=int, default=1000,
                        help="Save a structure shard every N steps.")
    parser.add_argument("--deposit-pace", type=int, default=500,
                        help="OPES kernel deposit frequency (steps).")
    parser.add_argument("--opes-barrier", type=float, default=5.0,
                        help="OPES barrier in kJ/mol.")
    parser.add_argument("--opes-biasfactor", type=float, default=10.0)
    parser.add_argument("--opes-sigma", type=str, default="0.3,0.5",
                        help="Per-CV kernel sigma (Angstrom): 'sigma_rmsd,sigma_pocket_dist'.")
    parser.add_argument("--temperature", type=float, default=300.0,
                        help="Langevin temperature (K).")
    parser.add_argument("--pocket-radius", type=float, default=6.0,
                        help="Pocket definition radius around ligand (Angstrom).")
    parser.add_argument(
        "--platform",
        type=str,
        default="CUDA",
        choices=["CUDA", "OpenCL", "CPU"],
        help="OpenMM platform (default: CUDA). CPU/OpenCL are fallbacks for "
        "machines without CUDA or for local debugging.",
    )
    parser.add_argument("--minimize-steps", type=int, default=1000,
                        help="Energy minimisation steps before MD.")
    parser.add_argument("--progress-every", type=int, default=10_000)
    parser.add_argument("--save-opes-every", type=int, default=50_000)
    parser.add_argument(
        "--opes-kernel-cutoff",
        type=float,
        default=None,
        metavar="SIGMA",
        help=(
            "Forwarded to the MD runner: PLUMED OPES_METAD KERNEL_CUTOFF. "
            "Omit for auto max(3.5, PLUMED default formula)."
        ),
    )
    parser.add_argument(
        "--opes-nlist-parameters",
        type=_parse_opes_nlist_parameters,
        default=None,
        metavar="A,B",
        help="Forwarded to the MD runner: OPES NLIST_PARAMETERS, e.g. '4.0,0.4'.",
    )
    parser.add_argument(
        "--opes-mode",
        type=str,
        default="plumed",
        choices=["plumed", "observer"],
        help=(
            "OPES mode for the OpenMM MD runner. 'plumed' uses PLUMED OPES_METAD "
            "(needs PLUMED built with --enable-modules=opes; stock conda-forge "
            "plumed lacks this — use a custom kernel or --opes-mode observer). "
            "'observer' is unbiased MD with Python OPESBias logging only."
        ),
    )
    parser.add_argument("--resume", action="store_true",
                        help="If final OPES outputs already exist, skip that system.")
    args = parser.parse_args()

    if args.opes_mode == "plumed":
        from genai_tps.simulation.plumed_kernel import assert_plumed_opes_metad_available

        assert_plumed_opes_metad_available()

    cache = Path(args.cache).expanduser() if args.cache else Path.home() / ".boltz"
    out_root = args.out.expanduser().resolve()
    out_root.mkdir(parents=True, exist_ok=True)

    selected_cases = {int(c.strip()) for c in args.cases.split(",")}

    campaign_log = []

    for idx, sys_def in enumerate(_SYSTEMS, start=1):
        if idx not in selected_cases:
            print(f"\n[00] Skipping {sys_def['name']} (not in --cases {args.cases})")
            continue

        print(f"\n{'='*60}")
        print(f"  System {idx}/3: {sys_def['description']}")
        print(f"{'='*60}", flush=True)

        system_out = out_root / sys_def["name"] / "openmm_opes_md"
        system_out.mkdir(parents=True, exist_ok=True)

        # Check for existing OPES state (resume logic)
        final_state = (
            system_out / "opes_states" / "STATE"
            if args.opes_mode == "plumed"
            else system_out / "opes_state_final.json"
        )
        if args.resume and final_state.is_file():
            print(f"  [00] Found existing OPES state at {final_state}; skipping.", flush=True)
            campaign_log.append({"case": sys_def["name"], "status": "skipped_resume"})
            continue

        yaml_path = _REPO_ROOT / sys_def["yaml"]
        if not yaml_path.is_file():
            raise FileNotFoundError(f"YAML input not found: {yaml_path}")

        # Step 1: Boltz preprocessing + one-shot structure sample for initial coords
        print(f"  [00] Boltz preprocessing and initial coordinates...", flush=True)
        bundle, topo_npz = _boltz_prep_for_openmm(
            yaml_path,
            system_out,
            cache,
            args.device,
            init_sampling_steps=args.init_sampling_steps,
            recycling_steps=args.recycling_steps,
        )
        from genai_tps.backends.boltz.inference import predict_sample_atom_coords_numpy

        print(
            f"  [00] Boltz-2 predict (sampling_steps={args.init_sampling_steps}, "
            f"recycling_steps={args.recycling_steps}) for MD initial pose...",
            flush=True,
        )
        init_coords = predict_sample_atom_coords_numpy(bundle)
        del bundle
        try:
            import torch

            torch.cuda.empty_cache()
        except Exception:
            pass

        frame_npz = system_out / "boltz_init_coords.npz"
        np.savez_compressed(frame_npz, coords=init_coords)
        print(f"  [prep] Initial coords NPZ: {frame_npz} ({init_coords.shape[0]} atoms)", flush=True)

        # Step 2: Run OpenMM OPES-MD
        opes_restart = None
        restart_path = (
            system_out / "opes_states" / "STATE"
            if args.opes_mode == "plumed"
            else system_out / "opes_states" / "opes_state_latest.json"
        )
        if args.resume and restart_path.is_file():
            opes_restart = restart_path
            print(f"  [00] Resuming OPES from {opes_restart}", flush=True)

        print(f"  [00] Running OpenMM OPES-MD ({args.n_steps:,} steps)...", flush=True)
        _run_openmm_md(
            topo_npz=topo_npz,
            frame_npz=frame_npz,
            mol_dir=cache / "mols",
            out_dir=system_out,
            n_steps=args.n_steps,
            save_every=args.save_every,
            deposit_pace=args.deposit_pace,
            opes_barrier=args.opes_barrier,
            opes_biasfactor=args.opes_biasfactor,
            opes_sigma=args.opes_sigma,
            temperature=args.temperature,
            pocket_radius=args.pocket_radius,
            platform=args.platform,
            minimize_steps=args.minimize_steps,
            progress_every=args.progress_every,
            save_opes_every=args.save_opes_every,
            opes_restart=opes_restart,
            opes_mode=args.opes_mode,
            opes_kernel_cutoff=args.opes_kernel_cutoff,
            opes_nlist_parameters=args.opes_nlist_parameters,
        )

        # Count output shards
        shard_count = len(list((system_out / "wdsm_samples").glob("wdsm_step_*.npz")))
        print(f"  [00] Done. {shard_count} shards written to {system_out / 'wdsm_samples'}", flush=True)
        campaign_log.append({
            "case": sys_def["name"],
            "status": "complete",
            "n_shards": shard_count,
            "out_dir": str(system_out),
            "topo_npz": str(topo_npz),
            "frame_npz": str(frame_npz),
        })

    # Write campaign log
    log_path = out_root / "00_reference_data_log.json"
    with open(log_path, "w") as fh:
        json.dump(campaign_log, fh, indent=2)
    print(f"\n[00] Campaign log: {log_path}", flush=True)
    print("[00] Stage 0 complete. Run 01_assemble_datasets.py next.", flush=True)


if __name__ == "__main__":
    main()
