#!/usr/bin/env bash
# build_plumed_opes.sh — Build PLUMED from the vendored plumed2 submodule with the
# OPES module enabled and install into the active conda prefix (overlays conda-forge
# libplumedKernel.so so OPES_METAD is available to openmm-plumed).
#
# Prerequisites:
#   - conda env created from environment.yml (includes plumed, openmm-plumed, build deps)
#   - git submodule at plumed2/ checked out to v2.9.x matching conda plumed pin
#
# Usage (from repo root, genai-tps activated):
#   conda activate genai-tps
#   git submodule update --init plumed2
#   git -C plumed2 checkout v2.9.2   # must match environment.yml plumed>=2.9,<2.10
#   bash scripts/build_plumed_opes.sh
#
# Then re-activate so activate.d exports PLUMED_KERNEL:
#   conda deactivate && conda activate genai-tps
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PLUMED_SRC="${REPO_ROOT}/plumed2"

if [[ -z "${CONDA_PREFIX:-}" ]]; then
  echo "[build_plumed_opes] ERROR: CONDA_PREFIX is unset. Activate your conda env first." >&2
  exit 1
fi

case "${CONDA_PREFIX}" in
  "" | "/" | "/usr" | "/usr/local")
    echo "[build_plumed_opes] ERROR: Refusing to install into CONDA_PREFIX=${CONDA_PREFIX}" >&2
    exit 1
    ;;
esac

if [[ ! -f "${PLUMED_SRC}/configure" ]]; then
  echo "[build_plumed_opes] ERROR: Missing ${PLUMED_SRC}/configure — run:" >&2
  echo "  git submodule update --init plumed2" >&2
  exit 1
fi

echo "[build_plumed_opes] CONDA_PREFIX=${CONDA_PREFIX}"
echo "[build_plumed_opes] PLUMED source: ${PLUMED_SRC}"

# Prefer conda compilers and pkg-config when present.
export PATH="${CONDA_PREFIX}/bin:${PATH}"
export PKG_CONFIG_PATH="${CONDA_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH:-}"

pushd "${PLUMED_SRC}" >/dev/null

if [[ -f Makefile ]]; then
  echo "[build_plumed_opes] Cleaning previous build tree (make distclean)..."
  make distclean >/dev/null 2>&1 || true
fi

echo "[build_plumed_opes] Configuring (modules=opes, MPI off, docs off, Python off)..."
# --enable-rpath: help the kernel find conda libs at runtime without extra LD_LIBRARY_PATH.
# --enable-mpi=no: matches typical OpenMM serial use; avoids requiring MPI headers.
./configure \
  --prefix="${CONDA_PREFIX}" \
  --enable-modules=opes \
  --enable-mpi=no \
  --enable-python=no \
  --disable-doc \
  --enable-rpath=yes

echo "[build_plumed_opes] Building and installing..."
make -j"$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)"
make install

popd >/dev/null

CFG="${CONDA_PREFIX}/lib/plumed/src/config/config.txt"
if [[ ! -f "${CFG}" ]]; then
  echo "[build_plumed_opes] ERROR: Expected ${CFG} after install." >&2
  exit 1
fi

echo "[build_plumed_opes] Verifying OPES module in ${CFG} ..."
if ! grep -q '^module opes on' "${CFG}"; then
  echo "[build_plumed_opes] ERROR: 'module opes on' not found in config.txt:" >&2
  grep '^module opes' "${CFG}" >&2 || true
  exit 1
fi

# Install conda activation hooks so OpenMM loads this kernel explicitly.
ACTIVATE_DIR="${CONDA_PREFIX}/etc/conda/activate.d"
DEACTIVATE_DIR="${CONDA_PREFIX}/etc/conda/deactivate.d"
mkdir -p "${ACTIVATE_DIR}" "${DEACTIVATE_DIR}"

cat >"${ACTIVATE_DIR}/plumed_opes_kernel.sh" <<'EOS'
# Generated by scripts/build_plumed_opes.sh — force OpenMM-Plumed to use this prefix kernel.
export PLUMED_KERNEL="${CONDA_PREFIX}/lib/libplumedKernel.so"
EOS

cat >"${DEACTIVATE_DIR}/plumed_opes_kernel.sh" <<'EOS'
unset PLUMED_KERNEL
EOS

echo "[build_plumed_opes] Wrote conda activate/deactivate hooks under etc/conda/."

# Optional Python check when genai-tps is importable from repo layout.
if PYTHONPATH="${REPO_ROOT}/src/python:${PYTHONPATH:-}" \
  python -c "from genai_tps.simulation.plumed_kernel import plumed_module_enabled; assert plumed_module_enabled('opes') is True" 2>/dev/null; then
  echo "[build_plumed_opes] Python check: plumed_module_enabled('opes') == True"
else
  echo "[build_plumed_opes] WARN: Skipped Python verify (install genai-tps editable or set PYTHONPATH=src/python)."
fi

echo "[build_plumed_opes] Done. Run: conda deactivate && conda activate genai-tps"
echo "[build_plumed_opes] Quick check: grep '^module opes' \"\${CONDA_PREFIX}/lib/plumed/src/config/config.txt\""
